### ISSUE TITLE
In 2.0.0, as_patch → "more argument specifiers than keyword list entries (remaining format:'b')"

### ISSUE THREAD

**Issue by nicwolff** [JoshData/fast_diff_match_patch#16]
Sorry to open an issue after you reacted so quickly to my question on #13 – and it's not a blocker for my current use case – but on at least recent Alpine Linux and Debian Slim the `as_patch` kwarg is now causing an error:
```
$ docker run -it python:alpine sh
/ # pip install fast-diff-match-patch
Collecting fast-diff-match-patch
  Downloading fast_diff_match_patch-2.0.0.post1-cp310-cp310-musllinux_1_1_x86_64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 2.7 MB/s 
Installing collected packages: fast-diff-match-patch
Successfully installed fast-diff-match-patch-2.0.0.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
/ # python
Python 3.10.0 (default, Nov 13 2021, 03:23:03) [GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fast_diff_match_patch import diff
>>> diff("Hello world.", "Goodbye moon.", as_patch=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: more argument specifiers than keyword list entries (remaining format:'b')
```
```
$ docker run -it python:slim sh
# pip install fast-diff-match-patch
Collecting fast-diff-match-patch
  Downloading fast_diff_match_patch-2.0.0.post1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (765 kB)
     |████████████████████████████████| 765 kB 3.2 MB/s 
Installing collected packages: fast-diff-match-patch
Successfully installed fast-diff-match-patch-2.0.0.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
# python
Python 3.9.7 (default, Sep  3 2021, 02:02:37) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fast_diff_match_patch import diff
>>> diff("Hello world.", "Goodbye moon.", as_patch=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: more argument specifiers than keyword list entries (remaining format:'b')
```

**Comment by JoshData** [comment]
Thanks! Fixed on main. I'll publish to pypi after waiting a bit in case other issues crop up.

**Comment by na-ka-na** [comment]
The pypi module still has this issue
